import Head from "next/head";
import React from "react";
import { type NextPage } from "next";

const ProfilePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Formula 1&trade; Takes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>Profile View</div>
      </main>
    </>
  );
}

export default ProfilePage;
